main: team.crazynetwork.raids.SkyBlockRaids
name: SkyBlockRaids
author: [SenpaiOfficial, CreeperFace0777, chanbakjsd]
version: 1.0
depends: ASkyblock

commands:
  island:
    aliases: is
    usage: /<command>
    description: Skyblock Island Command
